name: Run tests

on:
  push:
    branches: [latest]
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-20.04]
        python: [3.9]

    name: Python on ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - run: pip install -U pip setuptools

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
            activate-conda: true
      - run: conda env update -n base -f environment.yml

      - name: Install coverage dependencies
        run: pip install pytest-cov

      - name: Build
        run: python setup.py build_ext --inplace

      - name: Install grist
        run: pip install -e .

      - name: Install grist test deps
        run: pip install -e .[test]

      - run: pytest tests

#      - run: pytest tests --cov=.

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
